config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :travels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/travel.rb
# frozen_string_literal: true

class Travel < ApplicationRecord
  validates_presence_of :origin_address, :destination_address, message: "Can't be left empty"
  validates :meeting_duration, numericality: { other_than: 0 }
  validates_datetime :arrival_time,
                     after: DateTime.now
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/travels_controller.rb
# frozen_string_literal: true

require 'travel_time'
class TravelsController < ApplicationController
  def new
    @travel ||= Travel.new
    @time_default = DateTime.now + 40.minute
  end

  def index
    @travels = Travel.all
  end

  def destroy
    @travel = Travel.find(params[:id])
    if @travel.destroy
      flash[:success] = "Travel to #{@travel.destination_address} was successfully deleted."
      return redirect_to controller: 'travels', action: 'index'
    else
      flash[:error] = 'Something went wrong. Try again'
      return redirect_to controller: 'travels', action: 'index'
    end
  end

  def create
    arrival_datetime = get_arrival_time
    @travel = Travel.new(origin_address: params['origin_address'],
                         destination_address: params['destination_address'],
                         arrival_time: arrival_datetime,
                         meeting_duration: params['travel']['meeting_duration'].to_f)
    travel_time = TravelTime.get_travel_data(params['origin_address'], params['destination_address'], arrival_datetime)
    if travel_time
      @travel.update(travel_time: travel_time)
      if @travel.errors.any?
        error_messages = @travel.errors.full_messages.join(', ')
        flash[:danger] = "Errors: #{error_messages}"
      else
        flash[:success] = "It worked! Your travel time is #{travel_time} min"
        return redirect_to controller: 'travels', action: 'index'
      end
    else
      flash[:danger] = 'Something went wrong with the API call!'
    end
    redirect_to controller: 'travels', action: 'new'
  end

  private

  # def travel_params
  #   params.require(:travel).permit(:origin_address, :destination_address, :time_of_arrival)
  # end

  def get_arrival_time
    DateTime.new(
      params[:date][:year].to_i,
      params[:date][:month].to_i,
      params[:date][:day].to_i,
      params[:date][:hour].to_i,
      params[:date][:minute].to_i
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/travel_times/index.html.erb
<h2 class="text-center mt-4">What's your travel time? </h2>
<%= form_with(url: "/travel_times") do %>
  <div class="form-group">
    <%= label_tag(:origin_address, "Starting from:") %>
    <%= text_field_tag :origin_address, "65 Leonard Street, London", class: "form-control" %>
  </div>
  <div class="form-group">
  <%= label_tag(:destination_address, "Going to:") %>
  <%= text_field_tag :destination_address, nil, class: "form-control" %>
  </div>
  <%= submit_tag("Search", class: "btn btn-primary") %>
<% end %>
<iframe
  width="100%"
  frameborder="0" style="border:0"
  class="z-depth-1-half mt-3"
  src="https://www.google.com/maps/embed/v1/place?key=<%=ENV.fetch('GOOGLE_KEY')%>&q=65 Leonard Street,London" allowfullscreen>
</iframe>

app/views/travels/index.html.erb
<h2>List of travels</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Destination</th>
      <th>Time of arrival</th>
      <th>Travel time</th>
      <th>Duration of the Meeting (in min)</th>
      <th>Delete link</th>
    </tr>
  </thead>
  <tbody>
    <% @travels.each do |travel| %>
      <tr>
        <th><%= travel.destination_address %></th>
        <td ><%=travel.arrival_time%></td>
        <td ><%=travel.travel_time%></td>
        <td ><%=travel.meeting_duration%></td>
        <td ><%= button_to "Delete", travel_path(id: travel.id), method: :delete, class: "btn btn-outline-danger mt-1"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to "Create Travel", new_travel_path, method: :get, class: "btn btn-primary mt-1"%>

app/views/travels/new.html.erb
<h2 class="text-center mt-4">What's your travel time? </h2>
<%= form_with(url: "/travels") do %>
  <div class="form-group">
    <%= label_tag(:origin_address, "Starting from:") %>
    <%= text_field_tag :origin_address, "65 Leonard Street, London", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag(:destination_address, "Going to:") %>
    <%= text_field_tag :destination_address, nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag(:arrival_datetime, "Select the date and time of arrival:") %>
    <div class="row">
      <div class="col">
        <%= select_day @time_default, {include_blank: true}, {class: "form-control"}%>
      </div>
      <div class="col-1 text-center">-</div>
      <div class="col">
        <%= select_month @time_default,{}, {class: "form-control"}%>
      </div>
      <div class="col-1 text-center">-</div>
      <div class="col">
        <%= select_year @time_default, {}, {class: "form-control"}%>
      </div>
      <div class="col">
        <%= select_hour @time_default.utc ,{}, {class: "form-control"}%>
      </div>
      <div class="col-1 text-center">:</div>
      <div class="col">
        <%= select_minute @time_default.utc + 40.minute ,{}, {class: "form-control"}%>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag(:meeting_duration, "Duration of the meeting:") %>
    <%= select :travel, :meeting_duration, ["10 min", "30 min", "45 min", "60 min"], {include_blank: true}, class: "form-control" %>
  </div>
  <%= submit_tag("Search", class: "btn btn-primary") %>
<% end %>
<iframe
  width="100%"
  frameborder="0" style="border:0"
  class="z-depth-1-half mt-3"
  src="https://www.google.com/maps/embed/v1/place?key=<%=ENV.fetch('GOOGLE_KEY')%>&q=65 Leonard Street,London" allowfullscreen>
</iframe>